export const GET_DEMOGRAPHIC_OPTIONS = 'GET_DEMOGRAPHIC_OPTIONS';
export const GET_DEMOGRAPHIC_OPTIONS_SUCCESS = 'GET_DEMOGRAPHIC_OPTIONS_SUCCESS';
export const GET_DEMOGRAPHIC_OPTIONS_FAIL = 'GET_DEMOGRAPHIC_OPTIONS_FAIL';

export default {
  GET_DEMOGRAPHIC_OPTIONS,
  GET_DEMOGRAPHIC_OPTIONS_SUCCESS,
  GET_DEMOGRAPHIC_OPTIONS_FAIL,
};
