export const GET_DEMOGRAPHIC_OPTIONS = 'GET_DEMOGRAPHIC_OPTIONS';
export const GET_DEMOGRAPHIC_OPTIONS_SUCCESS = 'GET_DEMOGRAPHIC_OPTIONS_SUCCESS';
export const GET_DEMOGRAPHIC_OPTIONS_FAIL = 'GET_DEMOGRAPHIC_OPTIONS_FAIL';

export const GROUP_BY_DEMOGRAPHIC_OPTION = 'GROUP_BY_DEMOGRAPHIC_OPTION';
export const GROUP_BY_DEMOGRAPHIC_OPTION_SUCCESS = 'GROUP_BY_DEMOGRAPHIC_OPTION_SUCCESS';
export const GROUP_BY_DEMOGRAPHIC_OPTION_FAIL = 'GROUP_BY_DEMOGRAPHIC_OPTION_FAIL';


export default {
  GET_DEMOGRAPHIC_OPTIONS,
  GET_DEMOGRAPHIC_OPTIONS_SUCCESS,
  GET_DEMOGRAPHIC_OPTIONS_FAIL,
  GROUP_BY_DEMOGRAPHIC_OPTION,
  GROUP_BY_DEMOGRAPHIC_OPTION_SUCCESS,
  GROUP_BY_DEMOGRAPHIC_OPTION_FAIL,
};
