export const SEARCH_CENSUS = 'SEARCH_CENSUS';
export const SEARCH_CENSUS_SUCCESS = 'SEARCH_CENSUS_SUCCESS';
export const SEARCH_CENSUS_FAIL = 'SEARCH_CENSUS_FAIL';

export default {
  SEARCH_CENSUS,
  SEARCH_CENSUS_SUCCESS,
  SEARCH_CENSUS_FAIL,
};
